In [41]:
from SB_support import *
import pandas as pd

In [42]:
data = readSB(filename = "./original_data/chl-AL9807.sb", no_warn = True)

In [43]:
data.data

OrderedDict([('year',
              [1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998,
               1998]),
             ('month',
              [6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6]),
             ('day',
              [4,
               4,
               4,
               4,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               5,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               6,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               7,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               8,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               9,
               10,
               10,
               10,
               10,
               10,
               10,
               10,
               10,
               10,
               10,
               11,
               11]),
             ('hour',
              [15,
               15,
               21,
               21,
               9,
               9,
               2,
               2,
               15,
               15,
               18,
               18,
               20,
               20,
               22,
               22,
               0,
               0,
               1,
               1,
               5,
               5,
               11,
               11,
               15,
               15,
               19,
               19,
               23,
               23,
               3,
               3,
               9,
               9,
               12,
               12,
               15,
               15,
               19,
               19,
               22,
               22,
               2,
               2,
               9,
               9,
               6,
               6,
               12,
               12,
               14,
               14,
               18,
               18,
               22,
               22,
               1,
               1,
               4,
               4,
               7,
               7,
               13,
               13,
               16,
               16,
               22,
               22,
               6,
               6,
               4,
               4,
               10,
               10,
               15,
               15,
               20,
               20,
               2,
               2]),
             ('minute',
              [45,
               45,
               20,
               20,
               17,
               17,
               39,
               39,
               35,
               35,
               5,
               5,
               5,
               5,
               8,
               8,
               5,
               5,
               38,
               38,
               3,
               3,
               22,
               22,
               45,
               45,
               40,
               40,
               0,
               0,
               33,
               33,
               34,
               34,
               32,
               32,
               18,
               18,
               40,
               40,
               27,
               27,
               50,
               50,
               5,
               5,
               40,
               40,
               21,
               21,
               50,
               50,
               17,
               17,
               20,
               20,
               11,
               11,
               25,
               25,
               35,
               35,
               48,
               48,
               49,
               49,
               14,
               14,
               38,
               38,
               17,
               17,
               40,
               40,
               20,
               20,
               3,
               3,
               30,
               30]),
             ('lat',
              [41.0915,
               41.0915,
               40.4017,
               40.4017,
               40.5393,
               40.5393,
               40.5909,
               40.5909,
               41.1974,
               41.1974,
               41.0675,
               41.0675,
               40.9887,
               40.9887,
               41.2464,
               41.2464,
               41.4887,
               41.4887,
               41.69,
               41.69,
               41.4308,
               41.4308,
               41.4265,
               41.4265,
               41.7475,
               41.7475,
               41.8037,
               41.8037,
               42.0518,
               42.0518,
               42.0137,
               42.0137,
               42.6395,
               42.6395,
               42.6219,
               42.6219,
               42.4505,
               42.4505,
               42.1037,
               42.1037,
               42.3207,
               42.3207,
               42.797,
               42.797,
               42.8975,
               42.8975,
               42.7459,
               42.7459,
               43.0475,
               43.0475,
               43.3705,
               43.3705,
               43.4208,
               43.4208,
               43.6815,
               43.6815,
               43.9603,
               43.9603,
               44.3813,
               44.3813,
               44.3728,
               44.3728,
               43.9237,
               43.9237,
               43.7437,
               43.7437,
               43.2792,
               43.2792,
               43.1347,
               43.1347,
               43.3723,
               43.3723,
               42.4862,
               42.4862,
               42.1295,
               42.1295,
               42.1212,
               42.1212,
               42.3812,
               42.3812]),
             ('lon',
              [-68.1108,
               -68.1108,
               -68.0432,
               -68.0432,
               -67.0768,
               -67.0768,
               -67.5958,
               -67.5958,
               -66.7015,
               -66.7015,
               -67.06,
               -67.06,
               -67.3577,
               -67.3577,
               -67.4453,
               -67.4453,
               -67.6646,
               -67.6646,
               -67.7067,
               -67.7067,
               -67.1613,
               -67.1613,
               -66.1662,
               -66.1662,
               -66.3713,
               -66.3713,
               -66.8245,
               -66.8245,
               -67.2483,
               -67.2483,
               -67.7325,
               -67.7325,
               -67.9008,
               -67.9008,
               -67.5095,
               -67.5095,
               -66.988,
               -66.988,
               -66.3853,
               -66.3853,
               -65.9155,
               -65.9155,
               -65.9868,
               -65.9868,
               -67.0117,
               -67.0117,
               -66.5566,
               -66.5566,
               -67.4955,
               -67.4955,
               -67.7075,
               -67.7075,
               -67.2103,
               -67.2103,
               -66.5495,
               -66.5495,
               -66.9647,
               -66.9647,
               -66.6903,
               -66.6903,
               -67.314,
               -67.314,
               -68.5815,
               -68.5815,
               -69.1017,
               -69.1017,
               -69.9193,
               -69.9193,
               -68.8875,
               -68.8875,
               -68.6225,
               -68.6225,
               -68.6373,
               -68.6373,
               -68.7597,
               -68.7597,
               -69.6592,
               -69.6592,
               -70.3617,
               -70.3617]),
             ('chl',
              [1.7352,
               1.9521,
               1.446,
               1.55445,
               2.3859,
               2.42205,
               1.0122,
               1.0845,
               1.7352,
               1.84365,
               2.3859,
               2.2413,
               2.3859,
               2.3859,
               1.84365,
               2.06055,
               2.20515,
               2.3859,
               3.1089,
               2.9643,
               2.7474,
               2.6028,
               1.33755,
               1.26525,
               1.33755,
               1.26525,
               1.48215,
               1.40985,
               0.7953,
               0.7953,
               0.3856,
               0.39765,
               0.34945,
               0.3133,
               0.78325,
               0.78325,
               0.5061,
               0.54225,
               0.61455,
               0.6025,
               0.46995,
               0.4579,
               1.69905,
               1.48215,
               1.446,
               1.3737,
               1.1568,
               1.1568,
               0.5302,
               0.5061,
               0.5543,
               0.5302,
               0.59045,
               0.59045,
               2.78355,
               2.892,
               1.5906,
               1.55445,
               1.84365,
               1.84365,
               1.1568,
               1.0122,
               1.6629,
               1.5183,
               0.7712,
               0.7712,
               0.39765,
               0.39765,
               0.49405,
               0.5302,
               0.56635,
               0.56635,
               0.27474,
               0.27474,
               0.2892,
               0.28197,
               0.23136,
               0.24582,
               0.33981,
               0.33258])])

In [44]:
df = pd.DataFrame(data.data, columns=data.data.keys())

In [45]:
df

    year  month  day  hour  minute      lat      lon      chl
0   1998      6    4    15      45  41.0915 -68.1108  1.73520
1   1998      6    4    15      45  41.0915 -68.1108  1.95210
2   1998      6    4    21      20  40.4017 -68.0432  1.44600
3   1998      6    4    21      20  40.4017 -68.0432  1.55445
4   1998      6    5     9      17  40.5393 -67.0768  2.38590
..   ...    ...  ...   ...     ...      ...      ...      ...
75  1998      6   10    15      20  42.1295 -68.7597  0.28197
76  1998      6   10    20       3  42.1212 -69.6592  0.23136
77  1998      6   10    20       3  42.1212 -69.6592  0.24582
78  1998      6   11     2      30  42.3812 -70.3617  0.33981
79  1998      6   11     2      30  42.3812 -70.3617  0.33258

[80 rows x 8 columns]

In [46]:
#df1['key'] = df1['Order_ID'] + '_' + df1['Date'].apply(str)  # .apply(str) is new

#lambda function that puts a 0 in front of numbers that are less than 10 


df = df.assign(mod_minute = df["minute"].apply(str))
df['mod_minute'] = df['mod_minute'].apply(lambda x: x.zfill(2))

df = df.assign(complete_time = df["hour"].apply(str) + ":" + df["mod_minute"])
df = df.assign(complete_date = df["day"].apply(str) + "/" + df["month"].apply(str) + "/" + df["year"].apply(str))

In [47]:
df

,year,month,day,hour,minute,lat,lon,chl,mod_minute,complete_time,complete_date
0,1998,6,4,15,45,41.0915,-68.1108,1.73520,45,15:45,4/6/1998
1,1998,6,4,15,45,41.0915,-68.1108,1.95210,45,15:45,4/6/1998
2,1998,6,4,21,20,40.4017,-68.0432,1.44600,20,21:20,4/6/1998
3,1998,6,4,21,20,40.4017,-68.0432,1.55445,20,21:20,4/6/1998
4,1998,6,5,9,17,40.5393,-67.0768,2.38590,17,9:17,5/6/1998
...,...,...,...,...,...,...,...,...,...,...,...
75,1998,6,10,15,20,42.1295,-68.7597,0.28197,20,15:20,10/6/1998
76,1998,6,10,20,3,42.1212,-69.6592,0.23136,03,20:03,10/6/1998
77,1998,6,10,20,3,42.1212,-69.6592,0.24582,03,20:03,10/6/1998
78,1998,6,11,2,30,42.3812,-70.3617,0.33981,30,2:30,11/6/1998
79,1998,6,11,2,30,42.3812,-70.3617,0.33258,30,2:30,11/6/1998